# connection
DOBOT_DLL_RELATIVE_PATH = "./dobot_dll/DobotDll.dll"

SORT_DOBOT_BLE_MAC = "D4:AD:20:42:69:1E"
BASE_DOBOT_BLE_MAC = "9C:A5:25:EF:BA:6F"
HELP_DOBOT_BLE_MAC = "D4:AD:20:3F:E3:15"
# WH-BLE 102

BASE_ROBOT_COM = "COM4"
HELP_ROBOT_COM = "COM6"
SORT_ROBOT_COM = "COM8"

# boxes
BLUE_BOX_LDPos = 258
RED_BOX_LDPos = 650
GREEN_BOX_LDPos = 388
YELLOW_BOX_LDPos = 518
BOX_CONST_X = 228

BOX_X_OFFSET = 30
BOX_Y_OFFSET = BOX_X_OFFSET

BOX_Z_PLACE = -109
BOX_Z_MIN = -90

# base
BASE_LDPos = (0, 0)
BASE_CUBE_Z = 0

BASE_X_OFFSET = BOX_X_OFFSET
BASE_Y_OFFSET = BASE_X_OFFSET

# conv
CONV_POSSIBLE_MAX_SPEED = 41000
CONV_MAX_SPEED = 15500
CONV_MOVING_SPEED = 5000

CONV_BASE_3DPOS = (0, 0, 0) # x, y, z

# help
FREE_CUBE_OFFSET = 30
HELP_BASIC_POS = (0, 0)